<a href="https://colab.research.google.com/github/MrYelameli/gist/blob/main/numpy_zeros.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.random.random((3,4))

array([[0.58543529, 0.62524352, 0.16311814, 0.33874162],
       [0.03034065, 0.80045275, 0.42526938, 0.58205036],
       [0.8151677 , 0.16237733, 0.64838453, 0.29000542]])

In [ ]:
np.arange(0,6)

array([0, 1, 2, 3, 4, 5])